name: Lint Code Base

on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    name: linter
    env:
      VALIDATE_JAVASCRIPT_ES: false
      VALIDATE_JAVASCRIPT_STANDARD: false
      VALIDATE_CSS: false

    steps:
        - uses: actions/checkout@v2
        - uses: docker://github/super-linter:v2.1.0
